In [4]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [16]:
def conv_pytorch(image, conv_weights, stride = 1, pad = 1):
    image_tensor = torch.from_numpy(image)
    conv_weights_tensor = torch.from_numpy(conv_weights)
    output_tensor = torch.nn.functional.conv2d(image_tensor, conv_weights_tensor, stride = stride, padding = pad)

    return output_tensor.numpy()

In [28]:
array = np.array([[1, 2, 3]])
array = np.pad(array, ((2, 2), (2, 2)), "constant")
print(array)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [49]:
def conv_numpy_1(image, weights, stride = 1, pad = 1):
    
    batch_size, channels_in, image_height, image_width = image.shape
    channels_out, channels_in, kernel_height, kernel_width = weights.shape

    out_height = (int)((image_height + 2 * pad - kernel_height) / stride + 1)
    out_width = (int)((image_width + 2 * pad - kernel_width) / stride + 1)

    if pad != 0:
        image = np.pad(image, ((0, 0), (0, 0), (pad, pad), (pad, pad)), "constant")
    
    out = np.zeros((batch_size, channels_out, out_height, out_width))

    for c_batch in range(batch_size):
        for c_y in range(out_height):
            for c_x in range(out_width):
                for c_channel_out in range(channels_out):
                    for c_channel_in in range(channels_in):
                        for c_kernel_y in range(kernel_height):
                            for c_kernel_x in range(kernel_width):

                                out[c_batch, c_channel_out, c_y, c_x] += 0
### new test 01

    return out

In [50]:
np.random.seed(42)
n_batch = 1
image_height = 224
image_width = 224
channels_in = 1
kernel_size = 3
channels_out = 1

input_image = np.random.normal(size = (n_batch, channels_in, image_height, image_width))
conv_weights = np.random.normal(size = (channels_out, channels_in, kernel_size, kernel_size))
conv_results_pytorch = conv_pytorch(input_image, conv_weights, stride = 1, pad = 1)
# plt.imshow(conv_results_pytorch.reshape((image_height, image_width, 1)))
# plt.show()

print("Input shape: ", input_image.shape)
print("Kernel shape: ", conv_weights.shape)

out = conv_numpy_1(input_image, conv_weights)
print("Output shape: ", out.shape)
print("Output pytorch shape: ", conv_results_pytorch.shape)

Input shape:  (1, 1, 224, 224)
Kernel shape:  (1, 1, 3, 3)
Output shape:  (1, 1, 224, 224)
Output pytorch shape:  (1, 1, 224, 224)
